import '../styles/index.css'
import '../styles/index.css'
export { default as ConfigProvider } from './config-provider/index'
export type { ConfigProviderProps } from './config-provider/index'
export type { IconProps } from './types/index'
export * from './page/index'
export * from './outline/index'