import '../styles/index.css'
export { default as Action } from './Action'
export { default as H1 } from './H1'
export { default as H2 } from './H2'
export { default as H3 } from './H3'
export { default as H8 } from './H8'
export { default as Word } from './Word'
